// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pelican.Services.ProductAPI.Data;

#nullable disable

namespace Pelican.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.3.23174.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pelican.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageLocalPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Crime, Psychology",
                            Description = "Fyodor Dostoyevsky",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Crime and Punishment",
                            Price = 25.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Children's Books",
                            Description = "Samad Behrangi",
                            ImageUrl = "https://placehold.co/602x402",
                            Name = "The Little Black Fish",
                            Price = 20.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Pholosophy",
                            Description = "Friedrich Nietzsche",
                            ImageUrl = "https://placehold.co/601x401",
                            Name = "Also Sprach Zarathustra",
                            Price = 30.0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Romantic",
                            Description = "Emily Brontë",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "The Wuthering Heights",
                            Price = 60.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
